#!/bin/bash

#Checking if the folder exists
if [ ! -d $HOME/recyclebin ]
then
	mkdir $HOME/recyclebin
fi

#Checking conditions
if [ $# -eq 0 ] #Checking if any file name was provided
then
	echo "No File Name Provided"
	exit 1
elif [ ! -e $1 ] #Checking if the file name exists
then
	echo "File with name $1 doesnot exist"
	exit 1
elif [ ! -d $1 ] #Checking if the name sent is a directory
then
	echo "Directory $1 cannot be removed"
	exit 1
elif echo $1 | grep -q "recycle" #Checking if the user is trying to delete the command
then
	echo "Attempting to delete recycle - OPERATION ABORTED!!!"
	exit 1
else
	

